version: '3.9'

services:
  mongo_db:
    image: mongo
    restart: always
    ports:
      - '2717:27017'
    volumes:
      - mongo_data:/data/db
    logging:
      driver: none

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: ./.env
    ports:
      - 3300:$PORT
    environment:
      - PORT=$PORT
      - MONGODB_URI=$MONGODB_URI
      - SECRETORPRIVATEKEY_JWT=$SECRETORPRIVATEKEY_JWT
    links:
      - mongo_db
    depends_on:
      - mongo_db
    volumes:
      - ./src:/usr/src/app/src

volumes:
  mongo_data:
